### ISSUE TITLE
[New Icon]: A cool new icon

### ISSUE THREAD

**Issue by dgmjr** [GayWebIcons/CDN#1]
### Preflight Checklist

- [X] I could not find the icon or any discussions of why it hasn't yet been inclued in any existing issues, docs, or discussions.
- [X] I agree to follow this project's [Code of Conduct](https://gaywebicons.xyz/CODEOFCONDUCT).
- [X] I have read and am following this repository's [Contribution Guidelines](https://gaywebicons.xyz/CONTRIBUTE).

### Contact Details

david@dgmjr.io

### What type of icon are you requesting?

Porn site

### What's the name of the brand or icon?

Plex

### Which icon(s) would you like to see added?

my own personal Plex

**Comment by iamtheantitwink** [comment]
We're not doing that.
